// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type FieldType string

const (
	FieldTypeCheckbox FieldType = "checkbox"
	FieldTypeRadio    FieldType = "radio"
	FieldTypeText     FieldType = "text"
)

func (e *FieldType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FieldType(s)
	case string:
		*e = FieldType(s)
	default:
		return fmt.Errorf("unsupported scan type for FieldType: %T", src)
	}
	return nil
}

type NullFieldType struct {
	FieldType FieldType `json:"field_type"`
	Valid     bool      `json:"valid"` // Valid is true if FieldType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFieldType) Scan(value interface{}) error {
	if value == nil {
		ns.FieldType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FieldType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFieldType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FieldType), nil
}

type CheckboxField struct {
	FormVersionID int64    `json:"form_version_id"`
	Idx           int64    `json:"idx"`
	Options       []string `json:"options"`
}

type CurrentFormVersion struct {
	FormID        int64 `json:"form_id"`
	FormVersionID int64 `json:"form_version_id"`
}

type FilledCheckboxField struct {
	FfID            int64    `json:"ff_id"`
	SelectedOptions []string `json:"selected_options"`
}

type FilledForm struct {
	TaskID        int64  `json:"task_id"`
	FormVersionID *int64 `json:"form_version_id"`
}

type FilledFormField struct {
	ID     int64     `json:"id"`
	TaskID *int64    `json:"task_id"`
	Idx    *int32    `json:"idx"`
	Ftype  FieldType `json:"ftype"`
	Filled *bool     `json:"filled"`
}

type FilledRadioField struct {
	FfID           int64   `json:"ff_id"`
	SelectedOption *string `json:"selected_option"`
}

type FilledTextField struct {
	FfID    int64   `json:"ff_id"`
	Content *string `json:"content"`
}

type Form struct {
	ID        int64       `json:"id"`
	CreatorID pgtype.UUID `json:"creator_id"`
}

type FormField struct {
	FormVersionID int64     `json:"form_version_id"`
	Idx           int64     `json:"idx"`
	Ftype         FieldType `json:"ftype"`
	Prompt        *string   `json:"prompt"`
	Required      bool      `json:"required"`
}

type FormVersion struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	FormID      int64              `json:"form_id"`
}

type RadioField struct {
	FormVersionID int64    `json:"form_version_id"`
	Idx           int64    `json:"idx"`
	Options       []string `json:"options"`
}

type Task struct {
	ID        int64              `json:"id"`
	ClientID  pgtype.UUID        `json:"client_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Status    *int32             `json:"status"`
	Slug      string             `json:"slug"`
}

type TextField struct {
	FormVersionID int64 `json:"form_version_id"`
	Idx           int64 `json:"idx"`
	Paragraph     *bool `json:"paragraph"`
}

type User struct {
	ID       pgtype.UUID `json:"id"`
	Username string      `json:"username"`
	Password string      `json:"password"`
}
